# Generated by Django 4.2.3 on 2023-07-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Carbinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbinet_name', models.CharField(max_length=100)),
                ('carbinet_description', models.TextField(max_length=200)),
                ('carbinet_image', models.ImageField(upload_to='alumni_carbinet_images')),
                ('president', models.CharField(max_length=100)),
                ('vice_president', models.CharField(max_length=100)),
                ('general_secretary', models.CharField(max_length=100)),
                ('secretary', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('deputy_speaker', models.CharField(max_length=100)),
                ('finance_manager', models.CharField(max_length=100)),
                ('deputy_finance_manager', models.CharField(max_length=100)),
                ('legal_advisor', models.CharField(max_length=100)),
                ('chief_editor', models.CharField(max_length=100)),
                ('deputy_chief_editor', models.CharField(max_length=100)),
                ('public_relations_manager', models.CharField(max_length=100)),
                ('deputy_public_relations_manager', models.CharField(max_length=100)),
                ('organizing_secretary', models.CharField(max_length=100)),
                ('deputy_organizing_secretary', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('deputy_project_manager', models.CharField(max_length=100)),
                ('events_manager', models.CharField(max_length=100)),
                ('deputy_events_manager', models.CharField(max_length=100)),
                ('mobiliser', models.CharField(max_length=100)),
                ('deputy_mobiliser', models.CharField(max_length=100)),
                ('inclusive_officer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='events_images')),
                ('event_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=100)),
                ('order_course', models.CharField(max_length=100)),
                ('order_yos', models.CharField(max_length=100)),
                ('order_email', models.EmailField(max_length=100)),
                ('order_contact', models.CharField(max_length=100)),
                ('order_exec_shirt', models.CharField(max_length=100)),
                ('order_tshirt', models.CharField(max_length=100)),
                ('order_sicaid', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('yos', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
