# Generated by Django 4.2.3 on 2023-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('hscode', models.CharField(max_length=10)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('measurement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_description', models.TextField()),
                ('converted_cif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('import_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withholding_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infrastructure_levy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
