# Generated by Django 4.2.3 on 2023-08-23 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0002_taxcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
