# Generated by Django 4.2.3 on 2023-08-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0003_taxcalculation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='environmental_levy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='form_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='registration_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='seating_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='infrastructure_levy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='measurement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
