# Generated by Django 4.2.4 on 2023-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0004_taxcalculation_engine_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10)),
                ('hs_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('unit_of_quantity', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
            ],
        ),
    ]
