# Generated by Django 4.2.4 on 2023-10-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0007_motorvehiclevalueguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehiclevalueguide',
            name='CIF',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='motorvehiclevalueguide',
            name='Engine',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
