# Generated by Django 4.2.4 on 2023-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0008_alter_motorvehiclevalueguide_cif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehiclevalueguide',
            name='CIF',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
