# Generated by Django 4.2.4 on 2023-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0009_alter_motorvehiclevalueguide_cif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehiclevalueguide',
            name='YearOfManufacture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
