# Generated by Django 4.2.4 on 2023-10-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0010_alter_motorvehiclevalueguide_yearofmanufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
