# Generated by Django 4.2.4 on 2023-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0011_taxcalculation_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='gross_weight',
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='measurement',
            field=models.DecimalField(blank=True, decimal_places=2, default='Kgs', max_digits=10, null=True),
        ),
    ]
