# Generated by Django 4.2.4 on 2023-10-24 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GeromaApp', '0012_remove_taxcalculation_gross_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='hscode_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
