# Generated by Django 4.2.4 on 2023-12-10 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GeromaApp', '0013_taxcalculation_hscode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(default='Blog_images/blog.jpg', upload_to='Blog_images')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('blog_category', models.CharField(max_length=255, verbose_name='Blog Category')),
                ('blog_body_introduction', models.TextField(verbose_name='Introduction')),
                ('blog_body_main', models.TextField(verbose_name='Main Content')),
                ('blog_body_conclusion', models.TextField(verbose_name='Conclusion')),
                ('blog_created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_updated_at', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=255, verbose_name='Author')),
                ('comment_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('comment_body', models.TextField(verbose_name='Comment Body')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_updated_at', models.DateTimeField(auto_now=True)),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='GeromaApp.blog')),
            ],
        ),
    ]
